In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
movies=pd.read_csv('Dataset/imdb-top-1000.csv')
movies.sample(5)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
165,Casino,1995,178,Crime,8.2,Martin Scorsese,Robert De Niro,466276,42438300.0,73.0
770,Control,2007,122,Biography,7.7,Anton Corbijn,Sam Riley,61609,871577.0,78.0
223,Mad Max: Fury Road,2015,120,Action,8.1,George Miller,Tom Hardy,882316,154058340.0,90.0
312,Rebecca,1940,130,Drama,8.1,Alfred Hitchcock,Laurence Olivier,123942,4360000.0,86.0
609,The Hobbit: The Desolation of Smaug,2013,161,Adventure,7.8,Peter Jackson,Ian McKellen,601408,258366855.0,66.0

In [66]:
genres=movies.groupby('Genre')

In [ ]:
# Applying builtin aggregation functions on groupby object

genres.sum()
genres.min()

TypeError: dtype 'str' does not support operation 'std'

In [11]:
# find the top 3 genres by total earning
movies.groupby('Genre').sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [12]:
movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(2)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Name: Gross, dtype: float64

In [15]:
# find the genre with highest avg imdb rating
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [25]:
# find director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [31]:
# find number of movies done by each actor
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)
# movies['Star1'].value_counts()

Star1
Tom Hanks               12
Robert De Niro          11
Clint Eastwood          10
Al Pacino               10
Humphrey Bogart          9
                        ..
Zbigniew Zamachowski     1
Zooey Deschanel          1
Çetin Tekindor           1
Éric Toledano            1
Aaron Taylor-Johnson     1
Name: Series_Title, Length: 660, dtype: int64

In [32]:
# find total number of groups 
len(movies.groupby('Genre'))

14

In [33]:
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [65]:
genres= movies.groupby('Genre')
genres.first()
genres.last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [39]:
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [41]:
genres.sample()
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [49]:
# agg method
# passing dict
genres.agg(
    {
        'Runtime':'mean',
        'IMDB_Rating':'mean',
        'No_of_Votes':'sum',
        'Gross':'sum',
        'Metascore':'min'
    }
)

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

In [64]:
genres.agg(['min','max','sum'])

                              Series_Title  \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                                \
                                           max
Genre
Action                                 Yôjinbô
Adventure                           Zombieland
Animation          Ôkami kodomo no Ame to Yuki
Biography                              Zerkalo
Comedy                Zindagi Na Milegi Dobara
Crime                        À bout de souffle
Drama                                Zwartboek
Family     Willy Wonka & the Chocolate Factory
Fantasy                              Nosferatu
Film-Noir                        The Third Man
Horror                               The Thing
Mystery                                Vertigo
Thriller                       Wait Until Dark
Western                 The Outlaw Josey Wales

                                                             Released_Year  \
                                                         sum           min
Genre
Action     The Dark KnightThe Lord of the Rings: The Retu...          1924
Adventure  InterstellarBack to the FutureInglourious Bast...          1925
Animation  Sen to Chihiro no kamikakushiThe Lion KingHota...          1940
Biography  Schindler's ListGoodfellasHamiltonThe Intoucha...          1928
Comedy     GisaengchungLa vita è bellaModern TimesCity Li...          1921
Crime      The GodfatherThe Godfather: Part II12 Angry Me...          1931
Drama      The Shawshank RedemptionFight ClubForrest Gump...          1925
Family     E.T. the Extra-TerrestrialWilly Wonka & the Ch...          1971
Fantasy                Das Cabinet des Dr. CaligariNosferatu          1920
Film-Noir   The Third ManThe Maltese FalconShadow of a Doubt          1941
Horror     PsychoAlienThe ThingThe ExorcistNight of the L...          1933
Mystery    MementoRear WindowVertigoShutter IslandKahaani...          1938
Thriller                                     Wait Until Dark          1967
Western    Il buono, il brutto, il cattivoOnce Upon a Tim...          1965

                                                                   Runtime  \
            max                                                sum     min
Genre
Action     2019  2008200320102001200219991980197719621954200019...      45
Adventure    PG  2014198520091981196819621959201319751963194819...      88
Animation  2020  2001199419882016201820172008199719952019200920...      71
Biography  2020  1993199020202011200220171995198420182013201320...      93
Comedy     2020  2019199719361931200919641940200120001973196019...      68
Crime      2019  1972197419571994200219991995199120192006199519...      80
Drama      2020  1994199919941975202019981946201420061998198819...      64
Family     1982                                           19821971     100
Fantasy    1922                                           19201922      76
Film-Noir  1949                                       194919411943     100
Horror     2017       19601979198219731968196120171978193320042001      71
Mystery    2012   200019541958201020121995197219381988201219981997      96
Thriller   1967                                               1967     108
Western    1976                                   1966196819651976     132

                      IMDB_Rating  ...  \
           max    sum         min  ...
Genre                              ...
Action     321  22196         7.6  ...
Adventure  228   9656         7.6  ...
Animation  137   8166         7.6  ...
Biography  209  11970         7.6  ...
Comedy     188  17380         7.6  ...
Crime      229  13524         7.6  ...
Drama      242  36049         7.6  ...
Family     115    215         7.8  ...
Fantasy     94    170         7.9  ...
Film-Noir  108    312         7.8  ...
Horror     122   1123         7.6  ...
Mystery    138   1429         7.6  ...
Thriller   108    108         7.8  ...
Western    165    593         7.8  ...

                                                       Star1 No_of_Votes  \
                                                         sum         min
Genre
Action     Christian BaleElijah WoodLeonardo DiCaprioElij...       25312
Adventure  Matthew McConaugheyMichael J. FoxBrad PittJürg...       29999
Animation  Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...       25229
Biography  Liam NeesonRobert De NiroLin-Manuel MirandaÉri...       27254
Comedy     Kang-ho SongRoberto BenigniCharles ChaplinChar...       26337
Crime      Marlon BrandoAl PacinoHenry FondaJohn Travolta...       27712
Drama      Tim RobbinsBrad PittTom HanksJack NicholsonSur...       25088
Family                               Henry ThomasGene Wilder      178731
Fantasy                             Werner KraussMax Schreck       57428
Film-Noir           Orson WellesHumphrey BogartTeresa Wright       59556
Horror     Anthony PerkinsSigourney WeaverKurt RussellEll...       27007
Mystery    Guy PearceJames StewartJames StewartLeonardo D...       33982
Thriller                                      Audrey Hepburn       27733
Western    Clint EastwoodHenry FondaClint EastwoodClint E...       65659

                                    Gross                             \
               max       sum          min          max           sum
Genre
Action     2303232  72282412       3296.0  936662225.0  3.263226e+10
Adventure  1512360  22576163      61001.0  874211619.0  9.496922e+09
Animation   999790  21978630     128985.0  873839108.0  1.463147e+10
Biography  1213505  24006844      21877.0  753585104.0  8.276358e+09
Comedy      939631  27620327       1305.0  886752933.0  1.566387e+10
Crime      1826188  33533615       6013.0  790482117.0  8.452632e+09
Drama      2343110  61367304       3600.0  924558264.0  3.540997e+10
Family      372490    551221    4000000.0  435110554.0  4.391106e+08
Fantasy      88794    146222  337574718.0  445151978.0  7.827267e+08
Film-Noir   158731    367215     449191.0  123353292.0  1.259105e+08
Horror      787806   3742556      89029.0  298791505.0  1.034649e+09
Mystery    1129894   4203004    1035953.0  474203697.0  1.256417e+09
Thriller     27733     27733   17550741.0   17550741.0  1.755074e+07
Western     688390   1289665    5321508.0   31800000.0  5.822151e+07

          Metascore
                min    max      sum
Genre
Action         33.0   98.0  10499.0
Adventure      41.0  100.0   5020.0
Animation      61.0   96.0   6082.0
Biography      48.0   97.0   6023.0
Comedy         45.0   99.0   9840.0
Crime          47.0  100.0   6706.0
Drama          28.0  100.0  19208.0
Family         67.0   91.0    158.0
Fantasy         NaN    NaN      0.0
Film-Noir      94.0   97.0    287.0
Horror         46.0   97.0    880.0
Mystery        52.0  100.0    633.0
Thriller       81.0   81.0     81.0
Western        69.0   90.0    313.0

[14 rows x 27 columns]

In [55]:
# looping on groups
df=pd.DataFrame(columns=movies.columns)
for group, data in genres:
    df=df.append(data[data['IMDB_Rating']==data['IMDB_Rating'].max()])

df

AttributeError: 'DataFrame' object has no attribute 'append'

In [61]:


df = pd.DataFrame({
    "Name": ["A", "B", "C", "D","E"],
    "Dept": ["IT", "HR", "IT", "HR","mca"],
    "Salary": [50000, 40000, 60000, 45000,89000]
})

print(df.groupby("Dept")["Salary"].mean())

Dept
HR     42500.0
IT     55000.0
mca    89000.0
Name: Salary, dtype: float64

In [62]:
for dept, group in df.groupby("Dept"):
    print("Department:", dept)
    print(group)
    print("----------")

Department: HR
  Name Dept  Salary
1    B   HR   40000
3    D   HR   45000
----------
Department: IT
  Name Dept  Salary
0    A   IT   50000
2    C   IT   60000
----------
Department: mca
  Name Dept  Salary
4    E  mca   89000
----------

In [67]:
genres.apply(min)

Genre
Action       Director
Adventure    Director
Animation    Director
Biography    Director
Comedy       Director
Crime        Director
Drama        Director
Family       Director
Fantasy      Director
Film-Noir    Director
Horror       Director
Mystery      Director
Thriller     Director
Western      Director
dtype: str

In [72]:
# find number of movies starting with A for each group
def foo(group):
    return group['Series_Title'].str.startswith('A').sum()

In [73]:
genres.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [74]:
# find ranking of each movie in the group accouding to IMDB score

def rank_movie(group):
    group['genre_rank']= group['IMDB_Rating'].rank(ascending=False)
    return group

In [75]:
genres.apply(rank_movie)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  genre_rank
Genre
Action   2        2303232  534858444.0       84.0         1.0
         5        1642758  377845905.0       94.0         2.0
         8        2067042  292576195.0       74.0         3.5
         10       1661481  315544750.0       92.0         3.5
         13       1485555  342551365.0       87.0         6.0
...                   ...          ...        ...         ...
Thriller 700        27733   17550741.0       81.0         1.0
Western  12        688390    6100000.0       90.0         1.0
         48        302844    5321508.0       80.0         2.0
         115       232772   15000000.0       74.0         3.0
         691        65659   31800000.0       69.0         4.0

[1000 rows x 10 columns]

In [80]:
# grouping on multiple cols

duo=movies.groupby(['Director','Star1'])
duo
duo.size()
duo.get_group(('Aamir Khan','Amole Gupte'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [85]:
# find the most earning actor -> director combo

duo['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [86]:
ipl=pd.read_csv('Dataset/deliveries.csv')
ipl.sample(5)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
74189,315,2,Kings XI Punjab,Pune Warriors,1,5,PC Valthaty,AC Gilchrist,AB Dinda,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
162478,7944,2,Sunrisers Hyderabad,Royal Challengers Bangalore,11,6,MK Pandey,KS Williamson,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
38275,164,1,Kings XI Punjab,Deccan Chargers,1,6,S Sohal,SM Katich,RJ Harris,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
136208,576,1,Mumbai Indians,Chennai Super Kings,15,6,AT Rayudu,KA Pollard,DR Smith,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
111065,469,1,Sunrisers Hyderabad,Delhi Daredevils,2,5,S Dhawan,AJ Finch,Mohammed Shami,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [94]:
# find the top 10 batsman in term of runs

ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [103]:
# find the batsman with max no of sixes

six=ipl[ipl['batsman_runs']==6]
six.groupby('batsman')['batsman'].count().sort_values(ascending=False).head()

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
Name: batsman, dtype: int64

In [111]:
# find batsman with most number of 4's and 6's in last 5 overs

temp_df=ipl[ipl['over']>15]
temp_df[(temp_df['batsman_runs']==4) | (temp_df['batsman_runs']==6)]
temp_df.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(1)

batsman
MS Dhoni    1548
Name: batsman, dtype: int64

In [115]:
# find v kohli's record against all teams

temp_df=ipl[ipl['batsman']=='V Kohli']
temp_df.groupby('bowling_team')['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [ ]:
# create a function that can return the highest score of any batsman

In [129]:
temp_df=ipl[ipl['batsman']== 'V Kohli']
temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

np.int64(113)

In [130]:
def highest(batsman):
    temp_df=ipl[ipl['batsman']==batsman]
    return temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head[0]

In [134]:
highest('V Kohli')

TypeError: 'method' object is not subscriptable